version: 2
jobs:
    build:
        docker:
            - image: node:11.10.1

        working_directory: ~/repo

        steps:
            - run:
                  name: Install LFTP
                  command: |
                      sudo apt-get update
                      sudo apt-get install lftp
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run:
                  name: Test
                  command: yarn test

            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Deploy
                  command: lftp sftp://${user}:${password}@${host} -e "mirror --reverse -v ./build ./molkky; quit"
