version: 2
jobs:
    build:
        docker:
            - image: node:11.10.1

        working_directory: ~/repo

        steps:
            - run:
                  name: Install LFTP
                  command: |
                      apt-get update
                      apt-get install lftp
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            # run tests!
            - run:
                  name: Test
                  command: yarn test

            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Deploy
                  command: |
                      lftp -c "set sftp:auto-confirm yes; open -u $SFTP_USERNAME,$SFTP_PASSWORD@ sftp://$SFTP_HOSTNAME; mirror --reverse -v ./build ./molkky; quit"
                      #lftp sftp://$SFTP_USERNAME:$SFTP_PASSWORD@$SFTP_HOSTNAME -c "sftp:auto-confirm yes"-e "mirror --reverse -v ./build ./molkky; quit"
